In [9]:
include("../../src/schemes/arakawa.jl")

J (generic function with 1 method)

In [10]:
A = ones(4, 4)
B = ones(4, 4)
dx = 1.0

1.0

In [12]:
J(dx, A, B)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [14]:
C = rand(3, 3)
D = rand(3, 3)

3×3 Matrix{Float64}:
 0.895726  0.108133  0.632072
 0.944586  0.248366  0.025618
 0.983362  0.93686   0.330787

In [16]:
J(dx, C, D)

3×3 Matrix{Float64}:
 -0.00431967  -0.00431967  -0.00431967
 -0.00431967  -0.00431967  -0.00431967
 -0.00431967  -0.00431967  -0.00431967

In [17]:
-J(dx, D, C)

3×3 Matrix{Float64}:
 -0.00431967  -0.00431967  -0.00431967
 -0.00431967  -0.00431967  -0.00431967
 -0.00431967  -0.00431967  -0.00431967

In [25]:
J(dx, D^2, C)

3×3 Matrix{Float64}:
 0.0244833  0.0244833  0.0244833
 0.0244833  0.0244833  0.0244833
 0.0244833  0.0244833  0.0244833

In [23]:
J(dx, C^2, D)

3×3 Matrix{Float64}:
 0.11515  0.11515  0.11515
 0.11515  0.11515  0.11515
 0.11515  0.11515  0.11515